### PR TITLE
improved readme to discuss iteration

### PR DESCRIPTION
**Pull request by SophieDeBenedetto**
added info on iteration and some examples + stronger instructions

@jmburges

### CODE REVIEW

**Comment by jmburges** [comment]
Do you want this exposition on iterating over hashes to be in this lab or separated out into a separate reading?

**Comment by SophieDeBenedetto** [comment]
Not sure. The intro to hashes unit it getting pretty long and there is an
upcoming readme/repl on more complex iteration and manipulation. what do
you think?

On Tue, Jul 7, 2015 at 4:45 PM, Joe Burgess notifications@github.com
wrote:

> Do you want this exposition on iterating over hashes to be in this lab or
> separated out into a separate reading?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/key-for-min-value/pull/3#issuecomment-119332026
> .

## 

Sophie DeBenedetto

**Comment by SophieDeBenedetto** [comment]
separated into new readme, then this lab

https://github.com/learn-co-curriculum/hash-iteration

On Tue, Jul 7, 2015 at 4:46 PM, Sophie DeBenedetto <
sophie.debenedetto@gmail.com> wrote:

> Not sure. The intro to hashes unit it getting pretty long and there is an
> upcoming readme/repl on more complex iteration and manipulation. what do
> you think?
> 
> On Tue, Jul 7, 2015 at 4:45 PM, Joe Burgess notifications@github.com
> wrote:
> 
> > Do you want this exposition on iterating over hashes to be in this lab or
> > separated out into a separate reading?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/learn-co-curriculum/key-for-min-value/pull/3#issuecomment-119332026
> > .
> 
> ## 
> 
> Sophie DeBenedetto

## 

Sophie DeBenedetto

**Comment by jmburges** [comment]
awesome

**Pull request merged**
